apiVersion: apps/v1
kind: Deployment
metadata:
  name: okwudjw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okwudjw
  template:
    metadata:
      labels:
        app: okwudjw
    spec:
      containers:
      - image: okteto.dev/okwudjw:latest
        name: okwudjw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0de55ad3-e603-49d3-a900-04234633aebf"
        - name: Vless_Path
          value: "/hskhdiw387"
        - name: Vmess_UUID
          value: "2587eb0b-ad42-4285-ba0b-d91ef9ce17aa"
        - name: Vmess_Path
          value: "/dtsefweg837"
        - name: Share_Path
          value: "/v2link"
